Easydict/Feature/EventMonitor/EZEventMonitor.m

Add apps for error kAXErrorAttributeUnsupported
- Keynote `com.apple.iWork.Keynote`
- Numbers `com.apple.iWork.Numbers`
- WeChat `com.tencent.xinWeChat`
- iBooks `com.apple.iBooksX`
- Freeform `com.apple.freeform`

Add apps for error kAXErrorAttributeUnsupported

---

Easydict/App/Base.lproj/Main.storyboard
Easydict/Feature/StatusItem/EZMenuItemManager.m
Easydict/Feature/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.h
Easydict/Feature/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m
Easydict/Feature/ViewController/Window/WindowManager/EZWindowManager.h
Easydict/Feature/ViewController/Window/WindowManager/EZWindowManager.m

resolve #151 
效果：
可能的问题：
1. menu bar 的 title 现在是 “Copy First Result”，因为觉得 “Copy First Translated Text” 太长了，不过它的 tips 是 后者。
2. shotcut 默认为了 ⇧+⌘+J，模仿 “Copy” 的快捷键，然后觉得 J 比较方便，不知道是否可以；其他的应用内快捷键现在也不可以自定义吧？

feat: add shortcut for copy first translated text

---

Easydict/Feature/EventMonitor/EZEventMonitor.m

**Changes**
add Firefox for error kAXErrorAttributeUnsupported to fix #166 
Have to enable this in Settings as well to make it working in Firefox

perf: add Firefox for error kAXErrorAttributeUnsupported

---

Easydict/App/Localizable.xcstrings
Easydict/Feature/Configuration/EZConfiguration.h
Easydict/Feature/Configuration/EZConfiguration.m
Easydict/Feature/PerferenceWindow/EZSettingViewController.m
Easydict/Feature/Service/Model/EZEnumTypes.h
Easydict/Feature/Service/Model/EZEnumTypes.m
Easydict/Feature/ViewController/Window/WindowManager/EZWindowManager.m

目前，划词翻译（快捷键划词）使用的是侧悬浮窗口，这和自动划词并不统一。所以增加一个选项以能够设置划词翻译使用迷你窗口：
可能的问题：选项前面的 label 设置为“划词翻译”好还是“快捷键划词”好？因为[文档](https://github.com/tisfeng/Easydict/blob/main/README.md?plain=1#L341)的描述使用的是划词翻译。

feat: choose window type for shortcut and mouse select translate

---

Easydict/App/Localizable.xcstrings
Easydict/Feature/PerferenceWindow/EZSettingViewController.m

- Add SC translation for Apple
- Add SC translation for Baidu
- Add SC translation for Youdao
- Add space between Chinese and English strings for TTS service in Settings
It seems that strings need to be manually added to String Catalog for NSLocalizedString 🤔

Update TTS relevant strings in Settings

---

Easydict.xcodeproj/project.pbxproj
Easydict/Feature/Service/Bing/EZBingLanguageVoice.swift
Easydict/Feature/Service/Bing/EZBingRequest.m

- Migrated EZBingLanguageVoice to Swift
- Added header `Easydict-Swift.h` in EZBingRequest.m
- Kept the original `EZBingLanguageVoice.h` and `EZBingLanguageVoice.m` file in the repo for fast reverts.

Migrate EZBingLanguageVoice to Swift

---

README.md
README_EN.md

This extension can check if Easydict is installed. If not, open it.

Update Popclip extension installation.

---

Easydict/Feature/ViewController/View/WordResultView/EZWordResultView.m

When scrollbar is enabled, there is an extra 11 width.
Close #193

[Bugfix] Update label width calculation logic

---

Easydict/Feature/ViewController/Window/WindowManager/EZLayoutManager.m

#302 placeholder text not fully display in mini window
increase the textview's min height.
after change:

bugfix: #302 placeholder text not fully display in mini window

---

Easydict/App/AppDelegate.m
Easydict/Feature/Service/Language/EZLanguageManager.m

#305 app language not follow language updates in system settings 
Test path:
1. Change primary language in MacOS system settings
2. Relauch app and check the app language

bugfix: app language not follow language updates in system settings 

---

Easydict/Feature/StatusItem/EZMenuItemManager.m

Remove `increaseMenuItemHeight` func to use default menu item height

bugfix: make menu item height using default value

---

Easydict/NewApp/View/SettingView/SettingView.swift

Keep the settings page windows all the same width to avoid strange animations.
Refer to  [PasteNow](https://pastenow.app/)'s settings page animation.
https://github.com/tisfeng/Easydict/assets/25194972/5f5d1041-7472-4c6d-9432-634a1045e483
https://github.com/tisfeng/Easydict/assets/25194972/9fd57bd4-365d-4018-8d5f-90398a4ef723

perf: adjust setting UI

---

Easydict/NewApp/View/SettingView/Tabs/DisabledAppTab.swift

`List` item views may refresh after selection changes. This change will prevent content refresh after each selection.
After select too many apps in the list, you may experience significant lag behaviors.

fix: disable app list lag issue

---

Easydict/Feature/PerferenceWindow/DisableAutoSelectTextViewController/EZDisableAutoSelectTextViewController.m
Easydict/NewApp/View/SettingView/Tabs/DisabledAppTab.swift

Settings could not open after uninstall an app in the disabled app list in AppKit mode, SwiftUI version will show empty content
reproduce steps:
1. add one app in the disabled app list
3. uninstall the app
4. open settings

fix: setting crash after uninstall app in disabled app list

---

Easydict.xcodeproj/project.pbxproj
Easydict/App/AppDelegate.h
Easydict/App/AppDelegate.m
Easydict/App/Base.lproj/Main.storyboard
Easydict/Feature/Configuration/Configuration.swift
Easydict/Feature/Configuration/EZConfiguration.h
Easydict/Feature/Configuration/EZConfiguration.m
Easydict/Feature/StatusItem/EZMenuItemManager.m
Easydict/NewApp/EasydictApp.swift
Easydict/NewApp/GlobalContext.swift
Easydict/NewApp/Utility/GlobalContext.swift
Easydict/NewApp/View/MenuItemView.swift

Fix `updaterController` difference in old and new app life circle. #363

[Refactor] Introduce `GlobalContext` and migrate the updater controller into it

---

Easydict/Feature/Service/Tencent/TencentTranslateType.swift

Since simplified & traditional Chinese are still not labeled as translatable to each other on the doc. I didn't remove the logic in transType so that these two can still be usable.
Closes #367

Add Traditional Chinese to TencentTranslateType dev

---

Easydict/Feature/ViewController/Storage/EZLocalStorage.m

Fix https://github.com/tisfeng/Easydict/issues/269 and https://github.com/tisfeng/Easydict/issues/372

fix: new services were disabled by mistake

---

Easydict/Feature/PerferenceWindow/EZSettingViewController.m
Easydict/NewApp/NewAppManager.swift

Since the new Settings page is mostly done, we can now expose a option to the user.
Unfinished:

perf: show new settings option in release mode

---

Easydict/Feature/PerferenceWindow/EZSettingViewController.m

should not expose `SwiftUI App Mode` option to macOS 13 below.

fix: not show beta feature for macOS 13 below

---

Easydict/App/Localizable.xcstrings
Easydict/Feature/Configuration/Configuration.swift
Easydict/Feature/Configuration/EZConfiguration.h
Easydict/Feature/Configuration/EZConfiguration.m
Easydict/Feature/PerferenceWindow/EZSettingViewController.m
Easydict/Feature/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m
Easydict/Feature/ViewController/Window/WindowManager/EZWindowManager.m
Easydict/NewApp/Configuration/Configuration+Defaults.swift
Easydict/NewApp/View/SettingView/Tabs/GeneralTab.swift

feat(Select Translate): keep previous result if selected text is empty when open Select Translate

---

Easydict.xcodeproj/project.pbxproj
Easydict.xcworkspace/xcshareddata/swiftpm/Package.resolved
Easydict/NewApp/View/MenuItemView.swift

#382 
Introduce one new package: https://github.com/orchetect/SettingsAccess
This workaround does nothing if running from Xcode, but running as a standalone app it will work according to doc.
But it seems to work well both from Xcode build or archive based on my test.

fix: Setting window fails to appear front

---

Easydict/NewApp/Utility/Protocol/ServiceSecretConfigreValidatable.swift
Easydict/NewApp/View/SettingView/Tabs/ServiceConfiguration/ServiceConfigurationSecretSectionView.swift

fix: stream service like OpenAI trigger multi Alert issue

---

Easydict/Feature/ViewController/Window/WindowManager/EZWindowManager.m

close #362 
also fixed the issue that uses the shortcut key `cmd` + `,` to popup settings window while the query window is shown.

bugfix: settings window display issue

---

Easydict/Feature/Service/Bing/EZBingService.m
Easydict/Feature/Service/Model/EZQueryService.m
Easydict/NewApp/Configuration/Configuration+Defaults.swift

Fix https://github.com/tisfeng/Easydict/issues/421

fix: validate Bing service always fails

---

Easydict/App/Localizable.xcstrings
Easydict/NewApp/View/SettingView/Tabs/AboutTab.swift
Easydict/NewApp/View/SettingView/Tabs/AdvancedTab.swift
Easydict/NewApp/View/SettingView/Tabs/GeneralTab.swift

Please tell me if I CVed the code right :)

Migrate Automatically Check for Updates toggle from About tab to General Tab

---

Easydict/Feature/ViewController/View/Titlebar/EZTitlebar.m

Solve: #454
Verified it works locally.

Add eudic2 detect #454

---

Easydict/App/Localizable.xcstrings
Easydict/Feature/Configuration/Configuration.swift
Easydict/Feature/PerferenceWindow/EZSettingViewController.m
Easydict/Feature/ViewController/View/Titlebar/EZTitlebar.h
Easydict/Feature/ViewController/View/Titlebar/EZTitlebar.m
Easydict/Feature/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.h
Easydict/Feature/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m
Easydict/Feature/ViewController/Window/BaseQueryWindow/EZBaseQueryWindow.m
Easydict/NewApp/Configuration/Configuration+Defaults.swift
Easydict/NewApp/View/SettingView/Tabs/GeneralTab.swift

Close https://github.com/tisfeng/Easydict/issues/86#issuecomment-2028535304

feat: add action to replace newline with space

---

Easydict/Swift/Service/OpenAI/Prompt.swift

The previous prompt may have triggered censorship, causing some Chinese LLM to be unable to translate, like [kimi](https://kimi.moonshot.cn/) 🥵

perf: improve OpenAI prompt, to avoid Chinese LLM censorship

---

Easydict/Swift/Service/OpenAI/OpenAIService.swift

It should not automatically query OpenAI if the usage status is `AlwaysOff`.

fix: openai usage status does not work

---

Easydict/objc/PerferenceWindow/EZPrivacyViewController.m
Easydict/objc/Utility/EZCategory/NSImage/NSImage+EZSymbolmage.h
Easydict/objc/Utility/EZCategory/NSImage/NSImage+EZSymbolmage.m
Easydict/objc/ViewController/View/Titlebar/EZTitlebar.m

before: 
after:
minor change on the quick setting button icon, make it more compact, with harmonious proportions

Optimize quick setting button icon

---

Easydict/App/Localizable.xcstrings
Easydict/Swift/View/SettingView/Tabs/ServiceConfigurationView/ServiceConfigurationSecretSectionView.swift
Easydict/objc/Service/Model/EZQueryResult.h
Easydict/objc/Service/Model/EZQueryResult.m
Easydict/objc/ViewController/View/WordResultView/EZWordResultView.m

Previously, the service validation page would simply display an error message without detailed error information when something went wrong, which could be confusing for users.
In addition, I've improved the code so that the error message for getting the validation service is consistent with the query action.

perf: improve validation error message

---

Easydict/Swift/Service/OpenAI/BaseOpenAIService.swift
Easydict/Swift/View/SettingView/Tabs/ServiceConfigurationView/QueryService+ConfigurableService/CustomOpenAIService+ConfigurableService.swift
Easydict/Swift/View/SettingView/Tabs/ServiceConfigurationView/ServiceConfigurationCells.swift
Easydict/objc/ViewController/View/LoadingAnimationView/EZLoadingAnimationView.m
Easydict/objc/ViewController/View/ResultView/EZResultView.m
Easydict/objc/ViewController/View/WordResultView/EZWordResultView.m
Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m
Easydict/objc/ViewController/Window/WindowManager/EZLayoutManager.m

https://github.com/tisfeng/Easydict/assets/25194972/9d09e48d-c5da-4c73-babd-c7aed26eafa0

perf: do not hide model button when loading

---

Easydict/Swift/View/SettingView/Tabs/ServiceConfigurationView/QueryService+ConfigurableService/CustomOpenAIService+ConfigurableService.swift
Easydict/Swift/View/SettingView/Tabs/ServiceConfigurationView/QueryService+ConfigurableService/OpenAIService+ConfigurableService.swift

When configuring the service, there is a noticeable lag when inputting a large amount of text quickly.

fix: optimize performance when enter a lot of text quickly

---

Easydict/objc/Utility/EZAudioUtils/EZAudioUtils.m

Fix #485 
Fixed the issue of being unable to disable the alert beep when wearing AirPods.

fix: set audio param AudioObjectPropertyAddress is wrong

---

Easydict.xcodeproj/project.pbxproj
Easydict/App/Localizable.xcstrings
Easydict/Swift/Feature/Configuration/Configuration+Defaults.swift
Easydict/Swift/Feature/Configuration/Configuration.swift
Easydict/Swift/Feature/GetSelectedText/AppleScriptUtils.swift
Easydict/Swift/View/SettingView/Tabs/TabView/GeneralTab.swift
Easydict/objc/EventMonitor/EZEventMonitor.m
Easydict/objc/PerferenceWindow/EZSettingViewController.m
Easydict/objc/Utility/EZAudioUtils/EZAudioUtils.m
Easydict/objc/ViewController/Window/WindowManager/EZWindowManager.m

Fix https://github.com/tisfeng/Easydict/issues/315 , #111, #83 , now Easydict won't interrupt music playback or make strange alert sounds.
Since we can modify the alert volume individually, so it doesn't affect the system volume, so I removed the `Disable Empty Copy Beep` option.

fix: turn off the alert volume instead of system volume

---

Easydict/App/EasydictApp.swift
Easydict/Swift/View/MenuItemView.swift
Easydict/objc/ViewController/View/Titlebar/EZTitlebar.m

closed https://github.com/tisfeng/Easydict/issues/528#issuecomment-2089805673

fix: remove fake window which the trick way to open setting

---

Easydict/objc/EventMonitor/EZEventMonitor.m
Easydict/objc/ViewController/View/Titlebar/EZTitlebar.m

Looks like 2.7.x has a break change? It works on 2.6.1.
I have been resolved this at 2.7.x
related with #454, #455

fix: eudic2 shortcut did not work

---

Easydict.xcodeproj/project.pbxproj
Easydict/Swift/Service/Gemini/GeminiService.swift
Easydict/Swift/Service/OpenAI/BaseOpenAIService.swift
Easydict/Swift/Utility/Throttler.swift

Fix https://github.com/tisfeng/Easydict/issues/541
When I designed this app, I didn't realize that there would be a stream service like OpenAI behind it, and its frequent refreshing of the TableView would lead to high CUP usage and even UI lagging, so I added a `Throttler` to limit the frequency of refreshing.
While this approach doesn't fundamentally solve the problem, it can greatly alleviate it.
Before we rewrote the query window using SwiftUI, this would be a temporary solution.

perf: throttle the stream completion to update UI

---

Easydict/Swift/View/AdvancedTabItemView.swift

Very quick PR
Changes from `var` to `let` in AdvancedTabItemView.swift for better performance

perf: change var to let in AdvancedTabItemView

---

Easydict/App/Info-debug.plist
Easydict/App/Info.plist
Easydict/App/InfoPlist.xcstrings

Fix https://github.com/tisfeng/Easydict/issues/608#issuecomment-2324617301
Fix https://github.com/tisfeng/Easydict/issues/667

fix: add NSAppleEventsUsageDescrip to info.plist to fix NSAppleScript unauthorized error

---

Easydict/objc/EventMonitor/EZEventMonitor.m

Fix https://github.com/tisfeng/Easydict/issues/608#issuecomment-2333408602

fix: do not use simulation key when AppleScipt failed if user disable forced get text

---

Easydict/Swift/Feature/Configuration/Configuration+Defaults.swift

Fix https://github.com/tisfeng/Easydict/issues/678
这类问题 https://github.com/tisfeng/Easydict/issues/663#issuecomment-2331735305  太多了，为了照顾新手用户，也为了减少重复 issue，我们还是默认启用【允许强制取词】选项吧。
我的错，当初就不该改它 🥲

fix: set enableForceGetSelectedText to true by default

---

Easydict/objc/Service/Apple/AppleDictionary/EZAppleDictionary.m

Fix https://github.com/tisfeng/Easydict/issues/677

fix: do not need to check text query type when querying apple dictionary

---

Easydict/App/Localizable.xcstrings
Easydict/Swift/View/SettingView/SettingView.swift
Easydict/Swift/View/SettingView/Tabs/TabView/AdvancedTab.swift
Easydict/Swift/View/SettingView/Tabs/TabView/GeneralTab.swift

If possible, let's try to keep the `GeneralTab` clean and simple, avoid confusing new users, and move some complex optional features to the `AdvancedTab`.

refactor: move query text process to AdvancedTab

---

Easydict/Swift/View/SettingView/Tabs/TabView/AdvancedTab.swift

fix: port config subtitle text wrap issue

---

Easydict.xcodeproj/project.pbxproj
Easydict.xcworkspace/xcshareddata/swiftpm/Package.resolved
Easydict/App/Localizable.xcstrings
Easydict/Swift/Service/Apple/AppleService.swift
Easydict/Swift/Service/Apple/TranslationService/TranslationManager.swift
Easydict/Swift/Service/Apple/TranslationService/TranslationService.swift
Easydict/Swift/Service/Apple/TranslationService/TranslationView.swift
Easydict/Swift/View/SettingView/Tabs/TabView/AdvancedTab.swift
Easydict/Swift/View/SettingView/Tabs/TabView/GeneralTab.swift
Easydict/objc/Service/Apple/EZAppleService.m

I moved some of the settings options from General to the Advanced tab.
I found that having each Section icon use the same color here https://github.com/tisfeng/Easydict/pull/696 makes it visually less easy to distinguish each Item.
I tried to use a fixed color order, e.g. `blue, green, orange, purple, red` for the color order of the Items in each Section, and it seems to work well.

refactor: move some general settings to advanced tab

---

Easydict/objc/ViewController/View/WordResultView/EZWordResultView.m

Fix https://github.com/tisfeng/Easydict/issues/698
Currently, the layout of the webView is incorrect, which causes the webView to be obstructed and unable to display the results of the Apple Dictionary.
It looks like there are many changes in the code, but in reality, only one conditional statement was added: when there is an `HTMLString`, only the webView is displayed, and the other layouts remain unchanged.

fix: apple dict webView layout is wrong

---

Easydict/objc/Service/DeepL/EZDeepLTranslate.m

Close https://github.com/tisfeng/Easydict/issues/709
Because DeepL's Source language and Target language are different, Source languages do not support language variants, such as zh-hans, so we need to remove language variants when using Source languages.
[DeepL Docs](https://developers.deepl.com/docs/zh/resources/supported-languages#source-languages)

feat: support zh-hant for DeepL

---

Easydict/Swift/Service/Gemini/GeminiService.swift

I received an email on Google deprecating Gemini 1.0
I'm removing Gemini 1.0 in the default model, current users should have no impact until Feb 2025 when Google ends the service.

Deprecate gemini 1.0 pro

---

Easydict/Swift/View/SettingView/Tabs/ServiceConfigurationView/ServiceConfigurationSecretSectionView.swift
Easydict/Swift/View/SettingView/Tabs/TabView/AboutTab.swift

Fix https://github.com/tisfeng/Easydict/issues/742

fix: alert text show up to 1000

---

Easydict.xcodeproj/project.pbxproj
Easydict.xcworkspace/xcshareddata/swiftpm/Package.resolved
Easydict/App/EasydictApp.swift
Easydict/Swift/View/SettingView/SettingView.swift
Easydict/Swift/View/SettingView/Tabs/TabView/AboutTab.swift

Fix https://github.com/tisfeng/Easydict/issues/750

fix: button on About cannot be clicked

---

Easydict/objc/EventMonitor/EZEventMonitor.m

Fix https://github.com/tisfeng/Easydict/issues/796
According to user log, the axError is 0, means `kAXErrorSuccess`, we need to add it to white list.
```
[2025-01-22 20:34:39.789 ● EZEventMonitor ● 680 ● ℹ️] -[EZEventMonitor shouldForceGetSelectedTextWithAXError:] ● Not use force get selected text: 0, 福昕高级PDF编辑器 (com.foxit-software.Foxit.PDF.Editor)
```

fix: enable force get selected text in advanced foxit pdf editor

---

Easydict/App/EasydictApp.swift
Easydict/Swift/View/MenuView/MainMenuCommand.swift
Easydict/Swift/View/Window/HostWindowManager.swift

Fix https://github.com/tisfeng/Easydict/issues/767#issuecomment-2618408473

fix: change to use AppKit to show about window

---

Easydict/Swift/Feature/Configuration/Configuration.swift
Easydict/objc/Utility/EZLog/EZLog.m

Fix https://github.com/tisfeng/Easydict/issues/805#issuecomment-2633515729
We should call `didSetAllowCrashLog()` when app launches to make sure enable or disable crash log.

fix: disable crash log is not working

---

Easydict/App/Localizable.xcstrings
Easydict/Swift/Feature/Configuration/ServiceConfigurationKey.swift
Easydict/Swift/Service/OpenAI/StreamService+UpdateResult.swift
Easydict/Swift/Service/OpenAI/StreamService.swift
Easydict/Swift/Utility/Extensions/String/String+Regex.swift
Easydict/Swift/View/SettingView/Tabs/ServiceConfigurationView/ConfigurationView/StreamConfigurationView.swift
EasydictSwiftTests/Test.swift

Close https://github.com/tisfeng/Easydict/issues/806

feat: add an option to hide <think> tag content, hidden by default

---

Easydict/Swift/Service/Youdao/YoudaoService.swift

Fix https://github.com/tisfeng/Easydict/issues/836#issuecomment-2710845022
Make sure ocr completion in main thread.

fix: youdao ocr completion in non-main thread cause crash

---

Easydict/Swift/Service/Volcano/VolcanoResponse.swift
Easydict/Swift/Service/Volcano/VolcanoService.swift

Fix Volcano Translate error.
It seems that the structure of the Volcano Translate response has changed. Previously, Extra was a String, but now it is a Dictionary.
[Volcano Docs](https://www.volcengine.com/docs/4640/65067) is too bad 😡
```json
{
"TranslationList": [
{
"Translation": "好",
"DetectedSourceLanguage": "",
"Extra": { "input_characters": "4", "source_language": "en" }
}
],
"ResponseMetadata": {
"RequestId": "20250408103303ED54F9E8A6CC5E8853D6",
"Action": "TranslateText",
"Version": "2020-06-01",
"Service": "translate",
"Region": "cn-north-1"
}
}
```
Now
Fixed

fix: change Volcano response Extra type from String to Dictionary

---

Easydict/objc/Service/Model/EZQueryResult.h
Easydict/objc/Service/Model/EZQueryResult.m
Easydict/objc/ViewController/View/ResultView/EZResultView.m
Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m

Implements the feature request in issue #912 https://github.com/tisfeng/Easydict/issues/845 .
The entire title bar of a result entry in Easydict is now clickable to expand or collapse the content. Previously, only the small arrow icon could be used for this action.
Changes:
- Added an NSClickGestureRecognizer to the `topBarView` in `EZResultView.m`.
- The gesture recognizer's action handler replicates the logic from the existing `arrowButton`'s click block to ensure consistent behavior.
- The `arrowButton` remains functional as before.
- Both clicking the title area and clicking the arrow button will now toggle the visibility of the result content and update the arrow icon's state.

feat: Make result view title area clickable to expand/collapse

---

Easydict/Swift/Feature/Shortcut/Model/ShortcutManager+Default.swift
Easydict/Swift/Feature/Shortcut/Model/ShortcutManager.swift
Easydict/Swift/Feature/Shortcut/View/KeyHolderWrapper.swift

Previously, some shortcuts intended for in-app use were incorrectly registered as system-wide hotkeys. This could lead to conflicts with other applications or system functions.
This commit refactors the shortcut management logic to clearly differentiate between global and in-app shortcuts. An explicit `globalActions` list has been introduced to define which actions should have global hotkeys. The binding function now verifies an action against this list before registering it with the `HotKeyCenter`, ensuring only designated shortcuts are active system-wide.
Bug introduced in https://github.com/tisfeng/Easydict/pull/953
Fix https://github.com/tisfeng/Easydict/issues/997 , https://github.com/tisfeng/Easydict/issues/992 , https://github.com/tisfeng/Easydict/issues/982

fix(shortcut): prevent in-app shortcuts from being registered globally
