Easydict/Feature/EventMonitor/EZEventMonitor.m
- Add PDF Expert for error kAXErrorAttributeUnsupported
- Fix #92
=> Add PDF Expert for error kAXErrorAttributeUnsupported

Easydict/Feature/ViewController/Cell/EZSelectLanguageCell.m, Easydict/Feature/ViewController/View/CustomButton/EZCopyButton/EZCopyButton.m, Easydict/Feature/ViewController/View/QueryView/EZQueryView.m, Easydict/Feature/ViewController/View/ResultView/EZResultView.m, Easydict/Feature/ViewController/View/Titlebar/EZTitlebar.m, en.lproj/Localizable.strings, zh-Hans.lproj/Localizable.strings
Added 7 missing Simplified Chinese locales
Easydict v1.3.0
`Localization-updates` branch
=> perf: add missing localization

Easydict/Feature/EventMonitor/EZEventMonitor.m
- Add Zotero for error kAXErrorAttributeUnsupported
- Fix #98
=> Add Zotero for error kAXErrorAttributeUnsupported

Easydict/Feature/ViewController/View/ResultView/EZResultView.m, Easydict/Feature/ViewController/View/WordResultView/EZWordResultView.m, en.lproj/Localizable.strings, zh-Hans.lproj/Localizable.strings
- Add missing locales
- Update Simplified Chinese localization
=> Add missing localization

zh-Hans.lproj/Localizable.strings
使用 [Apple 支持](https://support.apple.com/zh-cn/guide/mac-help/mchlp1446/mac) 的命名：状态栏 -> 菜单栏
=> Update Chinese translation for menubar

README_EN.md
- Swift screenshots in English README with ones taken under the English interface.
- Fix typos
- Rename Settings View (Setting -> Settings)
=> Update Screenshots in English README

Easydict/App/Base.lproj/Main.storyboard, Easydict/App/mul.lproj/Main.xcstrings, Easydict/Feature/StatusItem/EZMenuItemManager.m
Close #159 
Fix https://github.com/tisfeng/Easydict/pull/195#issuecomment-1783134468
=> [Optimize] Fix storyborad text issue

Easydict/Feature/StatusItem/EZMenuItemManager.m
add a condition check before adding the status item
=> [Bugfix] Menu bar item not hidden after restart.

Easydict/Feature/Configuration/EZConfiguration.h, Easydict/Feature/Configuration/EZConfiguration.m, Easydict/Feature/DarkMode/DarkModeManager.m, Easydict/NewApp/NewAppManager.swift
修复这个循环引用报错 https://github.com/tisfeng/Easydict/pull/280#issuecomment-1872178490
=> fix: AppearenceType type error

Easydict/App/Info-debug.plist, Easydict/App/Info.plist, EasydictHelper/Info.plist
=> perf(UI): update copyright info

Easydict.xcodeproj/project.pbxproj
always getting `The file has been changed by another application` popup in Xcode while previewing SwiftUI views.
=> fix: swift format issue while enable SwiftUI preview

Easydict/App/Localizable.xcstrings
missing English translations in the Menu and General tab.
=> fix: add some missing English translations

Easydict/App/AppDelegate.m
=> Set appearance at launch

Easydict/Feature/ViewController/Window/WindowManager/EZWindowManager.m
close https://github.com/tisfeng/Easydict/issues/381
=> fix: query window dismissed in Stage Manager mode

Easydict/Feature/Configuration/Configuration.swift, Easydict/NewApp/Feature/Shortcut/Shortcut+Bind.swift
fix https://github.com/tisfeng/Easydict/issues/437
=> fix: font size index out of bounds

Easydict/App/AppDelegate.m
Close https://github.com/tisfeng/Easydict/issues/447
=> perf: do not dealloc main window when clicking close button

Easydict/Feature/ViewController/View/CustomButton/EZLinkButton/EZOpenLinkButton.m
close https://github.com/tisfeng/Easydict/issues/460
=> perf: do not close pinned window when clicking link button

Easydict/Feature/Service/Baidu/EZBaiduTranslate.m, Easydict/Feature/Service/Bing/EZBingRequest.m, Easydict/Feature/Service/Bing/EZBingService.m
close https://github.com/tisfeng/Easydict/issues/466
=> perf: do not update baidu cookie and bing host when initializing

Easydict/Feature/Service/Baidu/EZBaiduTranslate.m
#481 
先将接口相应切换到旧版本让服务可用，后面再做成可配置key的。
=> fix baidu translate

Easydict/Swift/View/SettingView/Tabs/ServiceTab.swift
https://github.com/tisfeng/Easydict/issues/491
=> fix: long service name make toggle disappear issue

Easydict/App/Localizable.xcstrings, Easydict/Swift/Service/Gemini/GeminiService.swift, Easydict/Swift/Service/OpenAI/BaseOpenAIService.swift, Easydict/objc/Service/Model/EZQueryResult.h, Easydict/objc/Service/Model/EZQueryResult.m, Easydict/objc/Service/Model/EZQueryService.h, Easydict/objc/Service/Model/EZQueryService.m, Easydict/objc/ViewController/View/ResultView/EZResultView.m, Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryWindow.m
Fixed #510 , and 
- enable to stop Gemini stream
https://github.com/tisfeng/Easydict/assets/25194972/5a18a321-3e11-4501-85a2-e259c2d9b75b
=> fix: stop button was gone when querying stream service

Easydict/App/Localizable.xcstrings, Easydict/objc/ViewController/Model/EZQueryModel.m, Easydict/objc/ViewController/View/ResultView/EZResultView.m, Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m
Close #480 
https://github.com/tisfeng/Easydict/assets/25194972/719bbabe-e7d8-487c-b97a-d23e1c609920
=> perf: enable to update single service rather than all services

Easydict/Swift/Feature/Localization/I18nHelper.swift, Easydict/Swift/Feature/Localization/LanguageState.swift
=> fix: improve local language

Easydict/Swift/Feature/Configuration/Configuration.swift, Easydict/objc/Configuration/EZConfiguration.m, README.md, README_EN.md
Fix https://github.com/tisfeng/Easydict/issues/502#issuecomment-2094206165 , and change to turn off  intelligent query mode for mini window.
=> fix: mini window intelligent query mode was enabled by mistake

Easydict/Swift/View/SettingView/Tabs/TabView/ServiceTab.swift, Easydict/objc/Service/Model/EZQueryService.m
#536 
Not sure if this issue is caused by the translation/sentence/dictionary option being disabled, you could try this and give me feedback if this issue still exists.
[screen-capture.webm](https://github.com/tisfeng/Easydict/assets/103433299/55edc690-e830-4050-9646-b7db2ed02894)
=> Service enable not work well issue

Easydict/App/Localizable.xcstrings, Easydict/objc/Snip/Snip.m
And  show alert if has no screen access.
Close https://github.com/tisfeng/Easydict/issues/587
=> perf: use CGRequestScreenCaptureAccess to get screen permission

Easydict/objc/Service/Youdao/EZYoudaoTranslate.m
Fix https://github.com/tisfeng/Easydict/issues/466#issuecomment-2192112812
=> fix: do not request Youdao cookie in init()

Easydict/objc/Service/Apple/EZAppleService.m
=> feat: support th-TH and vi-VT for Apple OCR languages

.swiftlint.yml, Easydict/App/Localizable.xcstrings, Easydict/Swift/Feature/Configuration/Configuration+Defaults.swift, Easydict/Swift/Feature/Configuration/Configuration.swift, Easydict/Swift/View/AdvancedTabItemView.swift, Easydict/Swift/View/SettingView/SettingView.swift, Easydict/Swift/View/SettingView/Tabs/TabView/AdvancedTab.swift, Easydict/objc/ViewController/View/CustomButton/EZReplaceTextButton/EZReplaceTextButton.m
Close https://github.com/tisfeng/Easydict/issues/622
=> feat: add a option replaceTranslationWithCompatibilityMode

Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m
Left is new animation, right is old.
https://github.com/user-attachments/assets/83e48d14-8227-401f-9444-d76846d4a91c
=> fix: improve update cell height animation

Easydict/Swift/View/SettingView/Tabs/TabView/ServiceTab.swift
Fix https://github.com/tisfeng/Easydict/commit/dced9d27b49875b6cf6ac386fee3526306b7a906
=> fix: move service refresh list

Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m
Fix https://github.com/tisfeng/Easydict/issues/644#issuecomment-2291355387
=> fix: use shortcut to show mini window with tips cell will cause crash

Easydict.xcodeproj/project.pbxproj, Easydict.xcworkspace/xcshareddata/swiftpm/Package.resolved, Easydict/Swift/Feature/Configuration/Configuration+Defaults.swift, Easydict/Swift/Feature/Configuration/Configuration.swift, Easydict/Swift/View/SettingView/Tabs/TabView/GeneralTab.swift
=> Refactor Launch At Login with launchatlogin-modern

Easydict.xcodeproj/project.pbxproj, Easydict/App/Localizable.xcstrings, Easydict/Swift/Feature/Localization/LanguageState.swift, docs/How-to-translate-Easydict-en.md, docs/How-to-translate-Easydict-zh.md
Add support for English (Canada)
=> Sample Localization PR

Easydict/App/InfoPlist.xcstrings, Easydict/App/Localizable.xcstrings, Easydict/Swift/Feature/Localization/LanguageState.swift, Easydict/objc/ViewController/View/CustomButton/LanguageButton/EZDetectLanguageButton.m
Closes #637 
Contribution from @Svec-Tomas 🙏
=> Slovak localization

Easydict/App/InfoPlist.xcstrings
Fixes https://github.com/tisfeng/Easydict/issues/637#issuecomment-2351589049
=> lang: fix Slovak localization

Easydict.xcworkspace/xcshareddata/swiftpm/Package.resolved, Easydict/objc/ViewController/View/ResultView/EZResultView.m
=> fix: model button hover title issue

Easydict/Swift/Service/Gemini/GeminiService.swift
在gemini中，当一个流在输出时，再进行另外一个词翻译，两个流就会穿插在一起。
=> fix: gemini stream error

Easydict.xcodeproj/project.pbxproj, Easydict/App/InfoPlist.xcstrings, Easydict/App/Localizable.xcstrings, Easydict/Swift/Feature/Localization/LanguageState.swift, docs/How-to-translate-Easydict-en.md, docs/How-to-translate-Easydict-zh.md
Closes #732 
Script to remove language in xcstring: https://stackoverflow.com/questions/77085342/how-to-remove-a-language-from-string-catalog
=> Remove en-CA localization & Update sample PR

Easydict/Swift/View/SettingView/Tabs/TabView/AboutTab.swift, Easydict/objc/EventMonitor/EZEventMonitor.m
Fix https://github.com/tisfeng/Easydict/issues/84#issuecomment-2528188384
=> fix: allow foxit to use force get selected text

Easydict/objc/Service/Youdao/EZYoudaoTranslate.m
Fix https://github.com/tisfeng/Easydict/issues/754#issuecomment-2558422606
=> fix: update Youdao web api secret key

Easydict/App/Info-debug.plist, Easydict/App/Info.plist, Easydict/App/InfoPlist.xcstrings, Easydict/Swift/View/SettingView/Tabs/TabView/AboutTab.swift
2024 -> 2025
Happy New Year everyone
=> Update copyright info

Easydict.xcodeproj/project.pbxproj, Easydict.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fix https://github.com/tisfeng/Easydict/issues/803#issuecomment-2635566465
=> fix: update Sentry to 8.44.0, to fix profiler cause memory leak

Easydict.xcodeproj/project.pbxproj, Easydict.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fix https://github.com/tisfeng/Easydict/security/dependabot/9
=> fix: update Sparkle to 2.6.4, to fix bypass signing check

Easydict/Swift/View/MenuView/MainMenuCommand.swift, Easydict/Swift/View/Window/HostWindowManager.swift
=> feat: add check for updates in menu

Easydict.xcodeproj/project.pbxproj, Easydict.xcworkspace/xcshareddata/swiftpm/Package.resolved, Easydict/Swift/Feature/Configuration/Configuration.swift
There is a potential menu bar freeze issue reported in Dafaults issues (https://github.com/sindresorhus/Defaults/issues/144).
Not sure if this related with our menu lagging issue, but worth a try.
=> fix: upgrade defaults

Easydict/Swift/Service/Gemini/GeminiService.swift
Close https://github.com/tisfeng/Easydict/issues/842
Docs: https://ai.google.dev/gemini-api/docs/models
=> fix: update gemini default models

Easydict/objc/EventMonitor/EZEventMonitor.m
Fix https://github.com/tisfeng/Easydict/issues/734 , https://github.com/tisfeng/Easydict/issues/844
=> fix: force get selected text option does not work in browser

Easydict/Swift/Utility/Screenshot/Screenshot/Screenshot+EventMonitor.swift, Easydict/Swift/Utility/Screenshot/Screenshot/Screenshot.swift, Easydict/Swift/Utility/Screenshot/Screenshot/ScreenshotState.swift
Fix https://github.com/tisfeng/Easydict/issues/867
=> fix: activate app after taking screenshot

Easydict/Swift/Utility/Screenshot/Screenshot/ScreenshotState.swift
Close https://github.com/tisfeng/Easydict/issues/860
=> feat: add enableDarkOverlay option, default to false

Easydict/objc/ViewController/Window/WindowManager/EZWindowManager.m
Fix https://github.com/tisfeng/Easydict/issues/858#issuecomment-2821031328
=> fix: restore wrong last application when switching applications by workspace

Easydict/objc/EventMonitor/EZEventMonitor.m
Fix https://github.com/tisfeng/Easydict/issues/868#issuecomment-2832027942
=> fix: cannot force get selected text in PowerPoint
